/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AgentBazaarRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentCount"
      | "agentExists"
      | "agents"
      | "getAgentsByOwner"
      | "ownerToAgents"
      | "registerAgent"
      | "setAgentStatus"
      | "updateMetadata"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentRegistered"
      | "AgentStatusChanged"
      | "MetadataUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentsByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerToAgents",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentStatus",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMetadata",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(functionFragment: "agentCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerToAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMetadata",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    owner: AddressLike,
    name: string,
    metadataCid: string
  ];
  export type OutputTuple = [
    agentId: bigint,
    owner: string,
    name: string,
    metadataCid: string
  ];
  export interface OutputObject {
    agentId: bigint;
    owner: string;
    name: string;
    metadataCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentStatusChangedEvent {
  export type InputTuple = [agentId: BigNumberish, active: boolean];
  export type OutputTuple = [agentId: bigint, active: boolean];
  export interface OutputObject {
    agentId: bigint;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MetadataUpdatedEvent {
  export type InputTuple = [agentId: BigNumberish, newMetadataCid: string];
  export type OutputTuple = [agentId: bigint, newMetadataCid: string];
  export interface OutputObject {
    agentId: bigint;
    newMetadataCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentBazaarRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentBazaarRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentBazaarRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentCount: TypedContractMethod<[], [bigint], "view">;

  agentExists: TypedContractMethod<[agentId: BigNumberish], [boolean], "view">;

  agents: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean] & {
        owner: string;
        name: string;
        metadataCid: string;
        createdAt: bigint;
        lastUpdatedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getAgentsByOwner: TypedContractMethod<
    [owner: AddressLike],
    [bigint[]],
    "view"
  >;

  ownerToAgents: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  registerAgent: TypedContractMethod<
    [name: string, metadataCid: string],
    [bigint],
    "nonpayable"
  >;

  setAgentStatus: TypedContractMethod<
    [agentId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;

  updateMetadata: TypedContractMethod<
    [agentId: BigNumberish, newMetadataCid: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agentExists"
  ): TypedContractMethod<[agentId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, boolean] & {
        owner: string;
        name: string;
        metadataCid: string;
        createdAt: bigint;
        lastUpdatedAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentsByOwner"
  ): TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "ownerToAgents"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [name: string, metadataCid: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgentStatus"
  ): TypedContractMethod<
    [agentId: BigNumberish, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMetadata"
  ): TypedContractMethod<
    [agentId: BigNumberish, newMetadataCid: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentStatusChanged"
  ): TypedContractEvent<
    AgentStatusChangedEvent.InputTuple,
    AgentStatusChangedEvent.OutputTuple,
    AgentStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "MetadataUpdated"
  ): TypedContractEvent<
    MetadataUpdatedEvent.InputTuple,
    MetadataUpdatedEvent.OutputTuple,
    MetadataUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(uint256,address,string,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentStatusChanged(uint256,bool)": TypedContractEvent<
      AgentStatusChangedEvent.InputTuple,
      AgentStatusChangedEvent.OutputTuple,
      AgentStatusChangedEvent.OutputObject
    >;
    AgentStatusChanged: TypedContractEvent<
      AgentStatusChangedEvent.InputTuple,
      AgentStatusChangedEvent.OutputTuple,
      AgentStatusChangedEvent.OutputObject
    >;

    "MetadataUpdated(uint256,string)": TypedContractEvent<
      MetadataUpdatedEvent.InputTuple,
      MetadataUpdatedEvent.OutputTuple,
      MetadataUpdatedEvent.OutputObject
    >;
    MetadataUpdated: TypedContractEvent<
      MetadataUpdatedEvent.InputTuple,
      MetadataUpdatedEvent.OutputTuple,
      MetadataUpdatedEvent.OutputObject
    >;
  };
}
